name        : sord
version     : 0.14.0
release     : 1
source      :
    - http://download.drobilla.net/sord-0.14.0.tar.bz2 : 7656d8ec56a43e0f0a168fe78670a7628a42d3a597b53c7a72ac243a74e0f19a
license     :
    - ISC
component   : programming.devel
summary     : Lightweight library for storing RDF data in memory
builddeps   :
    - serd-devel
description : Lightweight library for storing RDF data in memory 
setup       : |
    %workdir%/waf configure --prefix=%PREFIX% --libdir=%libdir%
build       : |
    %workdir%/waf build
install     : |
    %workdir%/waf install --destdir="$installdir"
