name       : sord
version    : 0.16.2
release    : 3
source     :
    - https://github.com/drobilla/sord/archive/v0.16.2.tar.gz : 8d99ac3ce98992460fb23ee6205d1174c33c0ec5de1a0d79cf9da5a3d686d070
license    : ISC
component  : programming.library
summary    : Lightweight library for storing RDF data in memory
description: Lightweight library for storing RDF data in memory
builddeps  :
    - pkgconfig(serd-0)
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
