name       : sord
version    : 0.16.4
release    : 4
source     :
    - git|https://github.com/drobilla/sord.git : v0.16.4
license    : ISC
component  : programming.library
summary    : Lightweight library for storing RDF data in memory
description: Lightweight library for storing RDF data in memory
builddeps  :
    - pkgconfig(serd-0)
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
