name       : sord
version    : 0.16.0
release    : 2
source     :
    - http://download.drobilla.net/sord-0.16.0.tar.bz2 : 9d3cb2c9966e93f537f37377171f162023cea6784ca069699be4a7770c8a035a
license    : ISC
component  : programming
summary    : Lightweight library for storing RDF data in memory
description: Lightweight library for storing RDF data in memory
builddeps  :
    - pkgconfig(serd-0)
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
